_target_: navsim.agents.drive_jepa_perception_based.drive_jepa_agent.DriveJEPAAgent
_convert_: 'all'

config:
  _target_: navsim.agents.drive_jepa_perception_based.drive_jepa_config.DriveJEPAConfig
  _convert_: 'all'

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

  latent: False

checkpoint_path: ''
lr: 1e-4
